@echo off

if defined JAVAFOLDER goto JAVAFOLDERDONE
set JAVAFOLDER=C:\Program Files (x86)\Java\jdk1.8.0_31\bin
set PATH=%PATH%;%JAVAFOLDER%
:JAVAFOLDERDONE

if defined WORKSPACE goto WORKSPACEDONE
set WORKSPACE=%CD%
set GNUWIN32FOLDER=%WORKSPACE%\tools\GnuWin32
set CLASSESFOLDER=%WORKSPACE%\classes
set OUTPUTFOLDER=%WORKSPACE%\output
set SOURCEFOLDER=%WORKSPACE%\src
set PATH=%PATH%;%WORKSPACE%;%GNUWIN32FOLDER%
:WORKSPACEDONE

set TARGETNAME=KMRobot

cmd